modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="treasure_seeker"
version="4.0.0"
displayName="Treasure seeker"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="orangejewce92"
description="Treasure seeker adds armor and tools."

[[dependencies.treasure_seeker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




